name: Test action
on: [push]
jobs:
    test_action:
        strategy:
            matrix:
                platform: [macos-14, macos-15, macos-15-intel, macos-26]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v6
            - run: make krc
